feat: change acc type of airdrop accs to vesting
CauchyE/utils pull request #7
Opened 2022-05-06 06:21 UTC by taikiFurusyo

I changed airdrop acc's type to ContinuousVestingAccount with preliminary start and end time.

Checked if this script works.
All added lines are commented out.

2022-05-09 13:45 UTC, mkXultra commented
pls, Activate code

2022-05-09 13:46 UTC, mkXultra requested changes

2022-05-09 13:46 UTC, mkXultra commented on genesis-operation/process-airdrop-operation.ts
> +// function processVestingAccounts(accInfo: any, amount: string) {
pls activate all code

2022-05-10 01:38 UTC, taikiFurusyo commented
I activated and set the right vesting period after checking if it works as intended.

Plz review, @mkXultra.

2022-05-10 02:06 UTC, merged