feat/airdrop-salvation
CauchyE/utils pull request #8
Opened 2022-05-06 10:32 UTC by taikiFurusyo

This PR is for users who submitted salvation form to take a chance of the airdrop again.

The target users are:
- Got scammed, but missed sending a form to recover it
- Put the address incorrectly
- Changed discord id and entered address in salvation form

2022-05-09 13:49 UTC, mkXultra requested changes

2022-05-09 13:49 UTC, mkXultra commented on genesis-operation/process-airdrop-operation.ts
> +const useSalvationList = false;
change false to true.

2022-05-09 13:49 UTC, mkXultra commented on genesis-operation/process-airdrop-operation.ts
> +    // index += 2;
Delete it

2022-05-09 13:50 UTC, mkXultra commented
@taikiFurusyo 
Is this PR a work in progress?

2022-05-10 01:15 UTC, taikiFurusyo commented
> @taikiFurusyo Is this PR a work in progress?

I forgot pushing.
Please review, @mkXultra .

2022-05-10 02:10 UTC, merged